/** Canonical English Bible book names (short → full) for normalization */
export const BOOK_ALIASES: Record<string, string> = {
  gn: "Genesis",
  gen: "Genesis",
  ex: "Exodus",
  exo: "Exodus",
  lv: "Leviticus",
  lev: "Leviticus",
  nm: "Numbers",
  num: "Numbers",
  dt: "Deuteronomy",
  deut: "Deuteronomy",
  jos: "Joshua",
  jdg: "Judges",
  ru: "Ruth",
  "1sa": "1 Samuel",
  "2sa": "2 Samuel",
  "1ki": "1 Kings",
  "2ki": "2 Kings",
  "1ch": "1 Chronicles",
  "2ch": "2 Chronicles",
  ezr: "Ezra",
  ne: "Nehemiah",
  neh: "Nehemiah",
  et: "Esther",
  est: "Esther",
  job: "Job",
  ps: "Psalms",
  psa: "Psalms",
  pr: "Proverbs",
  pro: "Proverbs",
  ec: "Ecclesiastes",
  ecc: "Ecclesiastes",
  so: "Song of Solomon",
  song: "Song of Solomon",
  is: "Isaiah",
  isa: "Isaiah",
  je: "Jeremiah",
  jer: "Jeremiah",
  la: "Lamentations",
  lam: "Lamentations",
  ek: "Ezekiel",
  eze: "Ezekiel",
  da: "Daniel",
  dan: "Daniel",
  ho: "Hosea",
  joe: "Joel",
  am: "Amos",
  ob: "Obadiah",
  jon: "Jonah",
  mic: "Micah",
  na: "Nahum",
  hab: "Habakkuk",
  zep: "Zephaniah",
  hag: "Haggai",
  zec: "Zechariah",
  mal: "Malachi",
  mt: "Matthew",
  matt: "Matthew",
  mk: "Mark",
  mrk: "Mark",
  lk: "Luke",
  luke: "Luke",
  jn: "John",
  joh: "John",
  ac: "Acts",
  act: "Acts",
  ro: "Romans",
  rom: "Romans",
  "1co": "1 Corinthians",
  "2co": "2 Corinthians",
  ga: "Galatians",
  gal: "Galatians",
  eph: "Ephesians",
  php: "Philippians",
  phil: "Philippians",
  col: "Colossians",
  "1th": "1 Thessalonians",
  "2th": "2 Thessalonians",
  "1ti": "1 Timothy",
  "2ti": "2 Timothy",
  tit: "Titus",
  phm: "Philemon",
  heb: "Hebrews",
  ja: "James",
  jas: "James",
  "1pe": "1 Peter",
  "2pe": "2 Peter",
  "1jn": "1 John",
  "2jn": "2 John",
  "3jn": "3 John",
  jude: "Jude",
  re: "Revelation",
  rev: "Revelation",
};
